In [3]:
#install needed libraries
import numpy as np
import matplotlib as pl
import seaborn as sb
import pandas as pd
from neo4j import GraphDatabase
import os

In [4]:
#connect to the database and estabilish that connection was successful
URI = "bolt://localhost:7687"
AUTH = ("neo4j","abcd90909090")

try:
    with GraphDatabase.driver(URI, auth=AUTH) as driver:
        driver.verify_connectivity()
        print("Connection established.")
except Exception as e:
    print("Error connecting to neo4j")
    print(e)

Connection established.

In [5]:
#define functions to use
#run_query attempts to run any query given to it
def run_query(query, parameters= None):
    try:
        with driver.session() as session:
            result = session.run(query, parameters)
            return [record.data() for record in result]
    except Exception as e:
        print(f"Error running query: {e}")
        return []

In [6]:
#runs a query to see how many CVEs are currently in the knowledge graph
CVE_count = """
    MATCH (n:UcoCVE)
    RETURN count(DISTINCT n)
"""

params = {}
count = run_query(CVE_count, parameters=params)

#creates a datafram to output the results
df = pd.DataFrame(count)

df

C:\Users\peyto\AppData\Local\Temp\ipykernel_29852\659216814.py:5: DeprecationWarning: Using a driver after it has been closed is deprecated. Future versions of the driver will raise an error.
  with driver.session() as session:

   count(DISTINCT n)
0             308297

In [7]:
#runs a query collecting all of the CVE nodes that are connected to CPE nodes through the UCOEXHASCPE relationship
query = """
MATCH (n:UcoCVE)-[UCOEXHASCPE]->(c:UcoexCPE)
RETURN count(DISTINCT n) as CVEs_with_CPEs
"""
records = run_query(query, parameters=params)

df = pd.DataFrame(records)
df

C:\Users\peyto\AppData\Local\Temp\ipykernel_29852\659216814.py:5: DeprecationWarning: Using a driver after it has been closed is deprecated. Future versions of the driver will raise an error.
  with driver.session() as session:

   CVEs_with_CPEs
0          264697